version: '3.8'

services:
  chat-analyzer-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat_analyzer
    
    ports:
      - "8000:8000"
      
    volumes:
      - ./config.json:/app/config.json:ro
      - sessions_data:/app/sessions
      - cache_data:/app/cache
      - ./bots.json:/app/bots.json 
      
    restart: unless-stopped

volumes:
  sessions_data:
  cache_data: